### ISSUE TITLE
Uncaught TypeError: editor.tokenizedLinesForScreenRows is not a function

### ISSUE THREAD

**Issue by iamlop** [mehcode/atom-symbols-plus#2]
**Atom Version**: 1.9.0
**System**: Mac OS X 10.11.6
**Thrown From**: [symbols-plus](https://github.com/mehcode/atom-symbols-plus) package, v0.1.1
### Stack Trace

Uncaught TypeError: editor.tokenizedLinesForScreenRows is not a function

```
At /Users/iamlop/Dropbox/Atom/.atom/packages/symbols-plus/lib/generator.js:68

TypeError: editor.tokenizedLinesForScreenRows is not a function
    at SymbolGenerator.getSymbolsForEditor (/Users/iamlop/Dropbox/Atom/.atom/packages/symbols-plus/lib/generator.js:68:26)
    at FinderView.populate (/Users/iamlop/Dropbox/Atom/.atom/packages/symbols-plus/lib/finder-view.js:90:36)
    at FinderView.toggle (/Users/iamlop/Dropbox/Atom/.atom/packages/symbols-plus/lib/finder-view.js:54:12)
    at atom-workspace.symbolsPlusToggleFileSymbols (/Users/iamlop/Dropbox/Atom/.atom/packages/symbols-plus/lib/symbols-plus.js:20:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -4:30.7.0 remote-ftp:toggle (atom-pane.pane.active)
  2x -4:28.4.0 git-projects:toggle (atom-pane.pane.active)
     -3:00.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -1:19.5.0 symbols-plus:toggle-file-symbols (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "symbols-list"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "symbols-tree-view"
    ],
    "projectHome": "/Volumes/Macintosh HD 2/web"
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.10 (inactive)
color-picker, v2.2.2 (active)
disable-keybindings, v0.6.0 (active)
docker, v0.7.0 (inactive)
editorconfig, v1.4.1 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.17 (active)
git-projects, v1.17.0 (active)
git-time-machine, v1.5.3 (inactive)
goto-definition, v1.1.18 (active)
highlight-selected, v0.11.2 (active)
jquery-snippets, v11.0.0 (active)
language-docker, v1.1.6 (active)
language-ejs, v0.2.0 (active)
language-nginx, v0.6.1 (active)
linter, v1.11.14 (active)
linter-docker, v0.1.2 (active)
linter-phpcs, v1.4.0 (active)
on-save, v0.2.9 (active)
pigments, v0.31.2 (active)
project-manager, v2.9.7 (active)
rainbow-tabs, v2.2.1 (active)
react, v0.15.0 (active)
Remote-FTP, v0.8.3 (active)
rest-client, v1.2.0 (active)
symbols-list, v2.3.0 (inactive)
symbols-plus, v0.1.1 (active)
sync-settings, v0.7.2 (active)
tablr, v1.3.2 (active)
terminal-plus, v0.14.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by liam-ngy** [comment]
+1

**Comment by wzhangsz** [comment]
+1

**Comment by Timemashine** [comment]
+1

**Comment by yumicat** [comment]
+1
